create table if not exists city
(
    id                integer generated by default as identity
        primary key,
    creation_date     timestamp,
    modification_date timestamp,
    status            varchar(255),
    address           varchar(255),
    city_name         varchar(255)
);

alter table city
    owner to postgres;

create table if not exists car
(
    id                integer generated by default as identity
        primary key,
    creation_date     timestamp,
    modification_date timestamp,
    status            varchar(255),
    brand             varchar(255),
    color             varchar(255),
    model             varchar(255),
    price             double precision,
    city_id           integer
        constraint fkb7h0v1qtngg6qiw64obcpxdr8
            references city
);

alter table car
    owner to postgres;

create table if not exists roles
(
    id                integer generated by default as identity
        primary key,
    creation_date     timestamp,
    modification_date timestamp,
    status            varchar(255),
    role_name         varchar(255)
);

alter table roles
    owner to postgres;

create table if not exists users
(
    id                integer generated by default as identity
        primary key,
    creation_date     timestamp,
    modification_date timestamp,
    status            varchar(255),
    email             varchar(255),
    login_user        varchar(255),
    password_user     varchar(255),
    mobile            varchar(255),
    surname           varchar(255),
    user_name         varchar(255)
);

alter table users
    owner to postgres;

create table if not exists contract
(
    id                integer generated by default as identity
        primary key,
    creation_date     timestamp,
    modification_date timestamp,
    status            varchar(255),
    contract_number   varchar(255),
    passport          varchar(255),
    car_id            integer
        constraint fkixovqbw2hcpmeuelx4a7la9td
            references car,
    user_id           integer
        constraint fki6rphdb5rpnqnrp5twyk83jao
            references users
);

alter table contract
    owner to postgres;

create table if not exists user_roles
(
    role_id integer not null
        constraint fkh8ciramu9cc9q3qcqiv4ue8a6
            references roles,
    user_id integer not null
        constraint fkhfh9dx7w3ubf1co1vdev94g3f
            references users,
    primary key (role_id, user_id)
);

alter table user_roles
    owner to postgres;

